CREATE TABLE Maintain (
    BIN INT NOT NULL CHECK(BIN > 0),
    Staff_No CHAR(8) NOT NULL,
    Present BOOLEAN NOT NULL,
    PRIMARY KEY (BIN, Staff_No),
    FOREIGN KEY (BIN) REFERENCES Banquet(BIN),
    FOREIGN KEY (Staff_No) REFERENCES Staff(Staff_No)
)